### ISSUE TITLE
Why use vite-bundle-visualizer rather than rollup-plugin-visualizer?

### ISSUE THREAD

**Issue by mcmxcdev** [KusStar/vite-bundle-visualizer#13]
I recently came across this tool and was wondering what the advantages are over rollup-plugin-visualizer? (which I have already configured and set up properly)

Would be great to know so I can choose accordingly.

**Comment by KusStar** [comment]
This tool currently is a CLI wrapper of rollup-plugin-visualizer. You can use it without configuring your vite project plugin. Mainly for non-invasive DX.
