### ISSUE TITLE
heap out of memory while building

### ISSUE THREAD

**Issue by realgs** [KusStar/vite-bundle-visualizer#17]
Thanks for the repo!
Any possibility of passing parameters to `vite build` invoked internally by vite-bundle-analyzer?

My build script has to be invoked with 
`        "build": "NODE_OPTIONS=--max-old-space-size=8192 vite build",
`
to increase the heap size

related to https://github.com/vitejs/vite/issues/2433

**Comment by realgs** [comment]
Solved. You can add this environment variable before running vite-bundle-visualizer:
`NODE_OPTIONS=--max-old-space-size=8192  npx vite-bundle-visualizer`

**Comment by KusStar** [comment]
You don't need to pass NODE_OPTIONS down to `vite build`, just prepend it before any command. Try 

```shell
NODE_OPTIONS=--max-old-space-size=8192 vite-bundle-visualizer
```

**Comment by realgs** [comment]
just posted the solution, sorry for the mess. Might be helpful though for the others :) Thanks!
