### ISSUE TITLE
Mode config option

### ISSUE THREAD

**Issue by sigerello** [KusStar/vite-bundle-visualizer#19]
We currently use vite  this way: `vite build --mode stage`.
While running `npx vite-bundle-visualizer` it falls back to `production` mode, which is not what we want, so it would be cool if it will be possible to pass needed `mode` explicitly.

**Comment by KusStar** [comment]
Added `--mode or -m` argument in [vite-bundle-visualizer@1.2.1](https://www.npmjs.com/package/vite-bundle-visualizer/v/1.2.1)

```shell
npx vite-bundle-visualizer --mode staging
```
