### ISSUE TITLE
Use rollup-plugin-visualizer?

### ISSUE THREAD

**Issue by wparad** [KusStar/vite-bundle-visualizer#23]
Why does the top of the readme say `Use [rollup-plugin-visualizer](https://github.com/btd/rollup-plugin-visualizer).`?

**Comment by KusStar** [comment]
Cuz this lib is just a wrapper of `rollup-plugin-visualizer` and call vite's `build` in CLI for you. Vite's bundler is based on rollup.
https://github.com/KusStar/vite-bundle-visualizer/blob/d1725ff42a4173c797cd2250b5005cdff68646c3/index.js#L70-L90

**Comment by wparad** [comment]
So no one should use this library because it is deprecated now and should always instead use `rollup-plugin-visualizer` with the attached the configuration?

**Comment by KusStar** [comment]
> So no one should use this library because it is deprecated now and should always instead use `rollup-plugin-visualizer` with the attached the configuration?

This library provide a cli to build with bundle visualizer, without configuring plugin in vite.config.js manaully, for dx things. 
No one said this lib is deprecated.

**Comment by wparad** [comment]
So maybe make that clear at the top of the readme instead of just saying `Use rollup-plugin-visualizer` it should instead say:

```
In most scenarios you shouldn't need this library, the recommended solution is to add
`rollup-plugin-visualizer` directly to your vite configuration. However, if you are using
vite, and want to run the visualizer directly from your command line via a CLI command
instead without needing to build your site, now you have a solution with the
`vite-bundle-visualizer`.
```

**Comment by KusStar** [comment]
Updated README
