### ISSUE TITLE
custom entry-file

### ISSUE THREAD

**Issue by ab90467** [KusStar/vite-bundle-visualizer#6]
Hi! I'm wanted to use this fantastic tool on a home-made component-library but I have no index.html.

So my proposal is to add a new Option, like --input "path to entry-file",  in order to support custom entry-point.

```
src git:(master) npx vite-bundle-visualizer    
vite v3.1.7 building for production...
✓ 0 modules transformed.
Could not resolve entry module (index.html).
file:///Users/dummy/cat/node_modules/rollup/dist/es/shared/rollup.js:1858
        base = Object.assign(new Error(base.message), base);
                             ^

Error: Could not resolve entry module (index.html).
    at error (file:///Users/dummy/cat/bygr-frontend-tools/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.loadEntryModule (file:///Users/dummy/cat/node_modules/rollup/dist/es/shared/rollup.js:22369:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
```

**Comment by KusStar** [comment]
This tool is always trying to call your vite build command with visualizer plugin in cwd, maybe you can try redirect to target directory?

Or you can provide a demo project, I would try to figure out.

**Comment by riteshpanchal** [comment]
I have 2 vite config files in the project. It would be nice to able to use an input argument to point to the vite config file.

**Comment by KusStar** [comment]
> I have 2 vite config files in the project. It would be nice to able to use an input argument to point to the vite config file.

Released in https://www.npmjs.com/package/vite-bundle-visualizer/v/0.8.0

**Comment by abhishiv** [comment]
Hey @KusStar 

In my case, vite generates two js files( due to `import MyWorker from "../worker?sharedworker";`), but the report generated is only for index.js

Do you have a Idea of how can I generate a report for the worker file?

```
✓ 151 modules transformed.
dist/index.html                              3.91 kB │ gzip:  1.37 kB
dist/assets/logo-2c341a38.png                8.14 kB
dist/assets/apple-touch-icon-8057b775.png    8.35 kB
dist/assets/worker-6b9ccd69.js             381.47 kB
dist/assets/index-99b91fd2.css               2.73 kB │ gzip:  1.08 kB
dist/assets/index-c9b13b5d.js              202.35 kB │ gzip: 65.91 kB
✓ built in 1.67s
```

Thanks for the great module!

**Comment by KusStar** [comment]
[v0.9.0](https://www.npmjs.com/package/vite-bundle-visualizer/v/0.9.0) supports custom entry file with `--entry custom-entry`

**Comment by KusStar** [comment]
> Hey @KusStar
> 
> In my case, vite generates two js files( due to `import MyWorker from "../worker?sharedworker";`), but the report generated is only for index.js
> 
> Do you have a Idea of how can I generate a report for the worker file?
> 
> ```
> ✓ 151 modules transformed.
> dist/index.html                              3.91 kB │ gzip:  1.37 kB
> dist/assets/logo-2c341a38.png                8.14 kB
> dist/assets/apple-touch-icon-8057b775.png    8.35 kB
> dist/assets/worker-6b9ccd69.js             381.47 kB
> dist/assets/index-99b91fd2.css               2.73 kB │ gzip:  1.08 kB
> dist/assets/index-c9b13b5d.js              202.35 kB │ gzip: 65.91 kB
> ✓ built in 1.67s
> ```
> 
> Thanks for the great module!

You can try to use `--entry` option to visualize the worker bundle, if won't work, draft a new issue.
